import Privateparty from 'partyconnect';
import Link from 'next/link'
import { useState } from "react";
const party = new Privateparty({
  host: "/api"
})
import styles from '../styles/Home.module.css'
export default function API() {
  const [ jwt, setJwt ] = useState("")
  const generate = async () => {
    let session = await party.connect("admin")
    console.log("session", session)
    setJwt(session.jwt)
  }
  return (
    <main className='main'>
      <nav>
        <Link href="/api/privateparty/gate/admin?callback=/">Logout</Link>
      </nav>
      <h1>micronuron</h1>
      <div>
        <Link href="/deploy">
          <a className="menu-item">Deploy</a>
        </Link>
        <Link href="/generate">
          <a className="menu-item">Generate API Key</a>
        </Link>
      </div>
      <div className='section'>
        <h2>Generate an API key</h2>
        <div>Only the API key generated by the ADMIN will be valid</div>
        <button onClick={generate}>Generate API Key</button>
        <textarea value={jwt} readOnly />
      </div>
    </main>
  );
}
